title: Conference Deadlines 
# email: 
description: Countdowns to top SE, ML and DM conference deadlines
author: Lun Du

url: "https://lundu28.github.io/ConferenceDDL"
domain: "https://lundu28.github.io/ConferenceDDL"
baseurl: "/ConferenceDDL"

# twitter_username:
# twitter_hashtag: 
# github_username: 
# github_repo: 

markdown: kramdown
# ga_id:

include: ['_pages']
